param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
)

$ErrorActionPreference = 'Stop'

function Get-RepoRelativePath {
  param([string]$Path, [string]$Base)
  $resolved = (Resolve-Path $Path).Path
  return $resolved.Substring($Base.Length).TrimStart('\').Replace('\', '/')
}

function Get-SectionFiles {
  param(
    [string]$Path,
    [string]$Base,
    [string[]]$Include = @('*')
  )

  if (-not (Test-Path $Path)) {
    return @()
  }

  Get-ChildItem -Path $Path -File |
    Where-Object {
      foreach ($pattern in $Include) {
        if ($_.Name -like $pattern) { return $true }
      }
      return $false
    } |
    Sort-Object Name |
    ForEach-Object {
      [pscustomobject]@{
        Name = $_.Name
        RelativePath = Get-RepoRelativePath -Path $_.FullName -Base $Base
      }
    }
}

function Add-MarkdownList {
  param(
    [System.Collections.Generic.List[string]]$Lines,
    [object[]]$Items
  )

  foreach ($item in $Items) {
    $Lines.Add('- `' + $item.RelativePath + '`')
  }
}

$examplesLogs = @(Get-SectionFiles -Path (Join-Path $RepoRoot 'examples\logs') -Base $RepoRoot -Include @('*.json', '*.txt'))
$exampleScreens = @(Get-SectionFiles -Path (Join-Path $RepoRoot 'screenshots\examples') -Base $RepoRoot -Include @('*.png'))
$docsFiles = @(Get-SectionFiles -Path (Join-Path $RepoRoot 'docs') -Base $RepoRoot -Include @('*.md'))
$notesFiles = @(Get-SectionFiles -Path (Join-Path $RepoRoot 'notes') -Base $RepoRoot -Include @('*.md'))
$targets = @(Get-SectionFiles -Path (Join-Path $RepoRoot 'examples\targets') -Base $RepoRoot -Include @('*.json'))
$profiles = @(Get-SectionFiles -Path (Join-Path $RepoRoot 'examples\profiles') -Base $RepoRoot -Include @('*.json'))
$scenarios = @(Get-SectionFiles -Path (Join-Path $RepoRoot 'examples\scenarios') -Base $RepoRoot -Include @('*.json'))

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Evidence Index')
$lines.Add('')
$lines.Add('Generated: ' + (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))
$lines.Add('')
$lines.Add('This file is generated by `scripts/dev/generate_evidence_index.ps1`.')
$lines.Add('')
$lines.Add('## Fast Paths')
$lines.Add('')
$lines.Add('- `docs/repo-map.md`')
$lines.Add('- `docs/validation-path.md`')
$lines.Add('- `frontend/src/App.jsx`')
$lines.Add('')
$lines.Add('## Primary Objects')
$lines.Add('')
$lines.Add('Targets: ' + $targets.Count)
$lines.Add('')
Add-MarkdownList -Lines $lines -Items $targets
$lines.Add('')
$lines.Add('OCR profiles: ' + $profiles.Count)
$lines.Add('')
Add-MarkdownList -Lines $lines -Items $profiles
$lines.Add('')
$lines.Add('Scenarios: ' + $scenarios.Count)
$lines.Add('')
Add-MarkdownList -Lines $lines -Items $scenarios
$lines.Add('')
$lines.Add('## Evidence Logs')
$lines.Add('')
$lines.Add('Log and readback files: ' + $examplesLogs.Count)
$lines.Add('')
Add-MarkdownList -Lines $lines -Items $examplesLogs
$lines.Add('')
$lines.Add('## Example Screenshots')
$lines.Add('')
$lines.Add('Representative screenshots: ' + $exampleScreens.Count)
$lines.Add('')
Add-MarkdownList -Lines $lines -Items $exampleScreens
$lines.Add('')
$lines.Add('## Docs')
$lines.Add('')
Add-MarkdownList -Lines $lines -Items $docsFiles
$lines.Add('')
$lines.Add('## Notes')
$lines.Add('')
Add-MarkdownList -Lines $lines -Items $notesFiles
$lines.Add('')
$lines.Add('## Cross Reference Hints')
$lines.Add('')
$lines.Add('- `examples/logs/phase2-validation.json` <-> `notes/phase2-validation-results.md`')
$lines.Add('- `examples/logs/ocr-phase-*.json` <-> `notes/ocr-phase-validation-results.md`')
$lines.Add('- `examples/logs/phase3-*.json` <-> `notes/phase3-validation-results.md`')
$lines.Add('- `examples/logs/phase4-multi-target.json` <-> `notes/phase4-validation-results.md` <-> `examples/scenarios/single-config-multi-target.json`')

$targetPath = Join-Path $RepoRoot 'docs\evidence-index.md'
Set-Content -Path $targetPath -Value ($lines -join "`r`n") -Encoding UTF8
Write-Output ('Generated ' + $targetPath)
